sudo: false
language: node_js
node_js:
  - '8'
  - '6'
  - '4'
os:
  - linux
  - osx
cache:
  directories:
  - node_modules
install:
  - npm i -g npx
  - npm install
script:
  - node --version
  - npm --version
  - npx --version
  - node -e "console.log('RAM:', (require('os').totalmem() / 1e6).toFixed(3), 'MB')"
  - node -e "console.log('CPU:', require('os').cpus().length, 'x', require('os').cpus()[0].model)"
  - npm test
after_test:
  - npx codecov
